### ISSUE TITLE
Enter in the tags or edit summary boxes runs fixer rather than submit

### ISSUE THREAD

**Issue by mjpieters** [AstroCB/Stack-Exchange-Editor-Toolkit#43]
I make heavy use of the keyboard when editing, and muscle-memory has me hit the `ENTER` key after tabbing into the tags or summary text fields to save the edit.

Unfortunately, the SE Editor Toolkit button has hijacked that key; it'll run the fixer instead.   Can this behaviour be disabled please? I'd rather see an explicit keyboard binding for the tool button.

**Comment by Vincentyification** [comment]
Does CTRL + Enter work?

**Comment by mjpieters** [comment]
`CTRL-Enter` indeed works, I'd prefer for plain `Enter` to work however. Perhaps `CTRL-Enter` could be used for the fixer instead?

**Comment by AstroCB** [comment]
I believe the problem here is on SE's side; they must have hardcoded the index of the submit button or something. I'll see what I can do.

**Comment by AstroCB** [comment]
Well, this was a mess.

This is what they have set for the `keydown` listener; something in another handler is probably causing this:

    function (a) {return typeof f!="undefined"&&(!a||f.event.triggered!==a.type)?f.event.dispatch.apply(i.elem,arguments):b;}

It would make sense that it's hardcoded because changing the `button` that applies the fixes to a `li` element like the others in the toolbar seems to fix the issue. However, doing that breaks a lot of the styling, so I (to my later dismay) chose to modify the event listeners directly rather than trying to counteract what SE is doing (which is beyond my knowledge).

So, while this took much longer than it should have, I was able to remove all of the event listeners (which is actually impossible; I actually just clone the element without its listeners and replace the old one with its clone) and add a new one that submits the edits if you press enter in either the tag field or the edit summary field, in line with the default behavior).

You also may now use CTRL (or CMD) + Enter from either of the fields to activate the auto-editor to finish up anything you may have missed and generate an edit summary. This is actually quite useful – you can now do CTRL + Enter + Enter in succession to auto-edit and apply the edits quickly.

**Comment by mjpieters** [comment]
Wow, did not realise it'd be this much work for you. Thanks for fixing it so promptly, the combination of keyboard shortcuts works great for me now!

**Comment by AstroCB** [comment]
It wasn't too bad. Thanks for bringing it to our attention, though, because I recall having this issue before we did a big redesign and I seemed to have forgotten about it.
