### ISSUE TITLE
Ajax is not wrong

### ISSUE THREAD

**Issue by Tyler-H** [AstroCB/Stack-Exchange-Editor-Toolkit#45]
http://en.wikipedia.org/wiki/Ajax_%28programming%29 Ajax is the name for the technology. AJAX is a newer acronym born of pure luck. This plug-in should not be renaming Ajax to AJAX.

**Comment by AstroCB** [comment]
I think that this is more of a stylistic thing (and all caps is the style I prefer, so that's what I had it correct to when I originally wrote the script – it was more of a test regex to see what I could do for HTML), but now that some people are using it, it might be a good idea to take it out (or at least make it capitalize the first letter).

Also note that you can also customize it with your own rules (including taking out this one) if you'd like.

**Comment by AstroCB** [comment]
I'm closing this because I modified the default rule to only match "ajax" (all lowercase). The default behavior converts it to the all-caps acronym, but you can modify this to only capitalize the first letter if you'd like. Thanks!
