### ISSUE TITLE
Upvote/Downvote capitalization

### ISSUE THREAD

**Issue by Tyler-H** [AstroCB/Stack-Exchange-Editor-Toolkit#58]
Upvote and Downvote are not proper nouns (they are not even nouns or even gerunds); they should not be capitalized.

**Comment by Unihedro** [comment]
![image](https://cloud.githubusercontent.com/assets/5595067/12301188/b1d0622a-ba59-11e5-8118-14925ce639f3.png)
yeah no

**Comment by Unihedro** [comment]
Ignore that, I mistook "capitalization" for "pluralization". :P

**Comment by AstroCB** [comment]
Thanks for letting us know.

I was sifting through the code trying to figure out why I had this rule in here and I found this:

```
// This allows me to combine the upvote and downvote replacement schemes into one
} else if (replacement == "$1vote") {
    input = input.replace(expression, function(data, match1) {
        phrase = match1;
        return phrase + "vot";
    });
reasoning = reasoning.replace("$1", phrase.toLowerCase());
}
```

Turns out it was an experiment to see how I could use data collected from the match in order to create dynamic edit summaries, which I've utilized for the all-caps and iOS rules, in addition to a few others.

The 'voting' rule has been removed; thanks again.
